import {StrictMode,useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft,ArrowRight,Check,CheckCircle2,SlidersHorizontal,FlaskConical,X,Shapes,Download,Lightbulb,Flag,Printer,Users} from 'lucide-react';
import {questions,chapters,type Option,type Answers} from '../app/questions';
import {summarize,percent,csv,responseTable,summaryTable,EXTRA_OPTIONS,type SurveyRecord} from '../app/survey-summary';
import {surveyWorkbook} from '../app/xlsx-export';
import './site.css';

// Google Apps Script web app URL (deploy apps-script/Code.gs).
const API='';
const KEY='manoly-survey';

type Saved={id:string;name:string;answers:Answers;step:number;done:boolean};
type Entry=SurveyRecord&{done:boolean;updated:string};
const blank=():Saved=>({id:crypto.randomUUID(),name:'',answers:{},step:0,done:false});
function readSaved():Saved{try{return {...blank(),...JSON.parse(localStorage.getItem(KEY)||'{}')};}catch{return blank();}}

async function call(query='',init?:RequestInit){if(!API)throw new Error('لم يُربط الموقع بجدول Google بعد.');const r=await fetch(API+query,init);const d=await r.json();if(d.error)throw new Error(d.error);return d;}
// text/plain body keeps the request "simple", so Apps Script needs no CORS preflight.
const send=(s:Saved)=>call('',{method:'POST',body:JSON.stringify({id:s.id,name:s.name,answers:s.answers,done:s.done})});
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

function Picture({o}:{o:Option}){if(o.colors)return <div className="palette" aria-hidden="true"><div className="palette-swatches">{o.colors.map((c,i)=><span key={i} style={{background:c}}/>)}</div></div>;if(o.type)return <div className={'type-sample '+o.type} aria-hidden="true">Manoly<span>INTERNATIONAL</span></div>;if(o.scene!==undefined)return <div role="img" aria-label={o.label} className="scene" style={{backgroundPosition:`${(o.scene%3)*50}% ${Math.floor(o.scene/3)*100}%`}}/>;const Icon=({check:CheckCircle2,conditions:SlidersHorizontal,test:FlaskConical,no:X,shape:Shapes} as any)[o.icon||'shape'];return <div className={'symbol '+(o.icon||'shape')}><Icon aria-hidden="true" strokeWidth={1.6}/></div>}

function Survey(){
const [s,setS]=useState(readSaved),[mode,setMode]=useState(()=>{const x=readSaved();return x.done?'done':x.name?'play':'start';}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[example,setExample]=useState(false),[name,setName]=useState('');
useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(s));}catch{}},[s]);
async function act(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'تعذّر الاتصال.');}finally{setBusy(false);}}
const q=questions[s.step],a=s.answers[q.id]||{choice:'',note:''};
const setAnswer=(choice:string,note=a.note)=>setS(v=>({...v,answers:{...v.answers,[q.id]:{choice,note}}}));
const go=(step:number)=>{setS(v=>({...v,step}));setExample(false);setError('');};
function next(){if(!a.choice){setError('اختر الصورة الأقرب أو «غير متأكد» أو «خيار آخر».');return;}act(async()=>{await send(s);setNotice('حُفظت الإجابات');if(s.step===questions.length-1)setMode('review');else go(s.step+1);});}
function restart(){setS(blank());setName('');setMode('start');}
return <>
{mode==='start'&&<section className="start-layout"><div className="start-copy"><span className="eyebrow">اكتشاف هوية العلامة</span><h1>صِف علامة <em>منولي</em><br/>كما تراها.</h1><p className="lead">اختر الصور والألوان الأقرب لرؤيتك.<br/>إجابات العائلة تكشف شخصية العلامة واتجاهها للسنوات الخمس القادمة.</p><form onSubmit={e=>{e.preventDefault();if(name.trim()){setS(v=>({...v,name:name.trim()}));setMode('play');}}}><label htmlFor="name">بأي اسم نبدأ؟</label><input id="name" maxLength={60} required value={name} onChange={e=>setName(e.target.value)} placeholder="اسمك فقط" autoComplete="given-name"/><button className="primary">ابدأ اكتشاف العلامة<ArrowLeft size={20}/></button></form><p className="fine">دون كلمة مرور. الاسم للتعريف، وليس للتحقّق من الهوية.<br/>٢٤ سؤالًا مصوّرًا · لا إجابات صحيحة أو خاطئة</p></div><div className="start-art"><div className="art-title">اليوم <span>←</span> ٣ سنوات <span>←</span> ٥ سنوات</div><Picture o={{scene:4,label:'العائلة تبني رؤيتها'}}/><div className="color-ribbon"><span/><span/><span/><span/></div><div className="art-caption">كل اختيار يوضّح جزءًا من شخصية العلامة.</div></div></section>}
{mode==='play'&&<section className="play"><div className="game-meta"><span className="eyebrow">{chapters[q.chapter]}</span><span>{s.name} · {s.step+1} / ٢٤</span></div><progress className="bar" max={questions.length} value={s.step+1} aria-label="تقدم الإجابة"/><div className="chapter-track">{chapters.map((c,j)=><span className={j===q.chapter?'active':''} key={c}>{String(j+1).padStart(2,'0')} {c}</span>)}</div><div className="question-title"><h1>{q.title}</h1><p>{q.hint}</p></div><div role="radiogroup" aria-label={q.title} className={'picture-grid '+(q.id==='palette'?'palette-grid':'')}>{q.options.map(o=><label className={'choice '+(a.choice===o.label?'selected':'')} key={o.label}><Picture o={o}/><div className="choice-caption"><input type="radio" name={q.id} value={o.label} checked={a.choice===o.label} onChange={()=>setAnswer(o.label)}/><span><strong>{o.label}</strong>{o.description&&<small>{o.description}</small>}</span>{a.choice===o.label&&<Check size={18}/>}</div></label>)}</div><div className="below-cards"><div className="extra-options">{EXTRA_OPTIONS.map(label=><button type="button" key={label} className={'unsure '+(a.choice===label?'chosen':'')} aria-pressed={a.choice===label} onClick={()=>setAnswer(label)}>{label}</button>)}</div><button type="button" className="example-toggle" onClick={()=>setExample(!example)} aria-expanded={example}><Lightbulb size={19}/>وضّح لي بمثال</button></div>{example&&<div className="example"><div className="example-steps"><span>اختيار</span><ArrowLeft/><span>سبب</span><ArrowLeft/><span>أثر على العميل</span></div><p>{q.example}</p></div>}<label className="note-label" htmlFor="note">لماذا اخترت هذا؟ <span>اختياري — اذكر شرطك أو مثالًا</span></label><textarea id="note" maxLength={1200} value={a.note} placeholder="رأيك هو الجزء المهم من الصورة…" onChange={e=>setAnswer(a.choice,e.target.value)}/><div className="game-actions"><button className="primary" disabled={busy} onClick={next}>{busy?'جارٍ الحفظ…':s.step===questions.length-1?'راجع خريطة إجاباتك':'احفظ وتابع'}<ArrowLeft size={19}/></button><button className="secondary" disabled={busy||s.step===0} onClick={()=>go(s.step-1)}><ArrowRight size={18}/>السابق</button></div><p className="fine">تُحفظ إجاباتك عند المتابعة. عرض إجابات العائلة محمي بكلمة سر.</p></section>}
{mode==='review'&&<section className="review"><div className="section-title"><span className="eyebrow">اكتملت اختياراتك</span><h1>هذه رؤيتك. هل تعبّر عنك؟</h1><p>راجع الاختيارات قبل الإرسال النهائي. بعدها تُقفل الإجابات.</p></div><div className="review-grid">{questions.map((x,k)=><button className="review-item" key={x.id} onClick={()=>{go(k);setMode('play');}}><small>{k+1}. {x.title}</small><strong>{s.answers[x.id]?.choice||'لم يُجب'}</strong><span>تعديل</span></button>)}</div><button className="primary" disabled={busy} onClick={()=>act(async()=>{if(questions.some(x=>!s.answers[x.id]?.choice))throw new Error('أكمل اختيارات الأسئلة أولًا.');await send({...s,done:true});setS(v=>({...v,done:true}));setMode('done');})}>{busy?'جارٍ الإرسال…':'اعتمد إجاباتي'}<Check/></button></section>}
{mode==='done'&&<section className="waiting"><div className="done-icon"><Flag size={36}/></div><span className="eyebrow">وصلت إلى نهاية الرحلة</span><h1>شكرًا {s.name}، رؤيتك أصبحت جزءًا من الصورة.</h1><p>أُرسلت إجاباتك. يمكن لفرد آخر من العائلة البدء من هذا الجهاز.</p><div className="game-actions"><button className="secondary" onClick={restart}><Users size={18}/>مشارك جديد</button></div></section>}
{error&&<div className="error" role="alert">{error}</div>}{notice&&mode==='play'&&<div className="save-notice" role="status">{notice}</div>}
</>;}

function Admin(){
const [password,setPassword]=useState(''),[records,setRecords]=useState<Entry[]|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
async function load(pw:string){setBusy(true);setError('');try{const d=await call('?password='+encodeURIComponent(pw));setRecords(d.records);try{sessionStorage.setItem(KEY,pw);}catch{}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
useEffect(()=>{let pw='';try{pw=sessionStorage.getItem(KEY)||'';}catch{}if(pw){setPassword(pw);load(pw);}},[]);
function logout(){try{sessionStorage.removeItem(KEY);}catch{}setRecords(null);setPassword('');}
const csvBlob=(t:(string|number)[][])=>new Blob([csv(t)],{type:'text/csv;charset=utf-8'});
if(!records)return <><div className="section-title"><h1>إجابات العائلة</h1><p>أدخل كلمة السر للوصول إلى نتائج الاستبيان.</p></div><form onSubmit={e=>{e.preventDefault();load(password);}} className="answers-login"><label htmlFor="results-password">كلمة السر</label><input id="results-password" type="password" autoComplete="current-password" inputMode="numeric" value={password} onChange={e=>setPassword(e.target.value)} required maxLength={100}/><button className="primary" disabled={busy}>{busy?'جارٍ التحقّق…':'عرض الإجابات'}</button></form>{error&&<p className="error" role="alert">{error}</p>}</>;
const done=records.filter(r=>r.done).length;
return <><div className="section-title"><h1>إجابات العائلة</h1><p>{records.length} مشارك · {done} أكملوا</p></div><div className="toolbar no-print"><button className="primary" onClick={()=>download(csvBlob(responseTable(records)),'manoly-answers.csv')}><Download/>تنزيل الإجابات CSV</button><button className="secondary" onClick={()=>download(csvBlob(summaryTable(records)),'manoly-summary.csv')}><Download/>ملخّص النسب CSV</button><button className="secondary" onClick={()=>download(surveyWorkbook(records),'manoly-answers.xlsx')}><Download/>Excel</button><button className="secondary" onClick={()=>window.print()}><Printer/>طباعة / PDF</button><button className="secondary" disabled={busy} onClick={()=>load(password)}>{busy?'جارٍ التحميل…':'تحديث'}</button><button className="secondary" onClick={logout}>قفل الإجابات</button></div>{error&&<p className="error" role="alert">{error}</p>}<p className="method-note">تظهر الإجابات المحفوظة، بما فيها الاستبيانات غير المكتملة. النسبة من المجيبين عن كل سؤال؛ الناقص منفصل. هذه آراء العائلة، وليست قياسًا لرأي السوق.</p><div className="consensus-grid">{summarize(records).map(q=><article className={'consensus chapter-'+q.chapter} key={q.id}><h3>{q.title}</h3>{q.options.map((o,i)=><div className="vote" key={o.label}><div><span>{o.label}</span><b>{o.count} · {percent(o.percentage)}</b></div><div className="vote-track"><span style={{width:(o.percentage||0)*100+'%'}}/></div></div>)}<p className="missing-count">أجاب: {q.answered} / {q.total} · لم يُجب: {q.missing}</p></article>)}</div>{records.map((p,i)=><section className="person-map" key={i}><h2>{p.name}</h2><p>{p.done?'إجابات نهائية':'لم يُكمل الاستبيان بعد'}</p><div className="map-nodes">{questions.map(q=><div className={'map-node chapter-'+q.chapter} key={q.id}><small>{q.title}</small><strong>{p.answers[q.id]?.choice||'لم يُجب'}</strong><p>{p.answers[q.id]?.note||'دون تفسير إضافي'}</p></div>)}</div></section>)}</>;}

function App(){const [hash,setHash]=useState(location.hash);useEffect(()=>{const f=()=>setHash(location.hash);addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f);},[]);const admin=hash==='#answers';
return <main><header className="topbar no-print"><a className="wordmark" href="#" aria-label="بداية منولي">MANOLY<span>رؤية العائلة</span></a><a className="secondary" href={admin?'#':'#answers'}>{admin?'الاستبيان':'عرض الإجابات'}</a></header>{admin?<Admin/>:<Survey/>}<footer className="no-print">منولي • اكتشاف الهوية والرؤية <span>الصور توضيحية، وليست صورًا فعلية للشركة.</span></footer></main>;}

createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
