'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,CheckCircle2,SlidersHorizontal,FlaskConical,X,Shapes,Copy,Printer,Download,Lightbulb,Users,Flag} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Progress} from '@/components/ui/progress';
import {summarize,percent,EXTRA_OPTIONS,type SurveyRecord} from './survey-summary';
import {surveyWorkbook} from './xlsx-export';
import {questions,chapters,type Option,type Answers} from './questions';
type Data={room:string;revealed:boolean;count:number;complete:number;host?:boolean;me:null|{name:string;answers:Answers;done:boolean};participants?:{name:string;done:boolean}[];report?:{name:string;answers:Answers}[]};
function Picture({o}:{o:Option}){if(o.colors)return <div className="palette" aria-hidden="true"><div className="palette-swatches">{o.colors.map((c,i)=><span key={i} style={{background:c}}/>)}</div></div>;if(o.type)return <div className={'type-sample '+o.type} aria-hidden="true">Manoly<span>INTERNATIONAL</span></div>;if(o.scene!==undefined)return <div role="img" aria-label={o.label} className="scene" style={{backgroundPosition:`${(o.scene%3)*50}% ${Math.floor(o.scene/3)*100}%`}}/>;const Icon=({check:CheckCircle2,conditions:SlidersHorizontal,test:FlaskConical,no:X,shape:Shapes} as any)[o.icon||'shape'];return <div className={'symbol '+(o.icon||'shape')}><Icon aria-hidden="true" strokeWidth={1.6}/></div>}
export default function BrandDiscovery(){const [room,setRoom]=useState(''),[data,setData]=useState<Data|null>(null),[name,setName]=useState(''),[answers,setAnswers]=useState<Answers>({}),[step,setStep]=useState(0),[mode,setMode]=useState('start'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[example,setExample]=useState(false),[notice,setNotice]=useState('');
async function request(payload:any){const r=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذّر تنفيذ الطلب.');return d;}
async function load(id:string,initial=false){const r=await fetch('/api/game?room='+encodeURIComponent(id));const d:Data&{error?:string}=await r.json();if(!r.ok)throw new Error(d.error);setData(d);if(initial&&d.me){setAnswers(d.me.answers);setStep(Math.max(0,questions.findIndex(q=>!d.me!.answers[q.id])));setMode(d.me.done?'waiting':'play');}return d;}
useEffect(()=>{const id=new URLSearchParams(location.search).get('room')||'';setRoom(id);if(id)load(id,true).catch(e=>setError(e.message)).finally(()=>setReady(true));else setReady(true);},[]);
useEffect(()=>{if(!room||mode!=='waiting')return;const timer=setInterval(()=>{load(room).catch(e=>setError(e.message));},10000);return()=>clearInterval(timer);},[room,mode]);
useEffect(()=>{const c=(document as any).modelContext;if(!c?.registerTool)return;const controller=new AbortController();try{Promise.resolve(c.registerTool({name:'read_current_brand_question',description:'Read the current Manoly question and staged answer without saving.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode,question:mode==='play'?questions[step]:null,answer:answers[questions[step].id]||null})},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[mode,step,answers]);
async function act(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'تعذّر الاتصال.');}finally{setBusy(false);}}
function enter(){act(async()=>{const d=await request({action:room?'join':'create',room,name});setRoom(d.room);history.replaceState(null,'','?room='+d.room);await load(d.room,true);});}
const stats=summarize(data?.report||[]);
const q=questions[step],a=answers[q.id]||{choice:'',note:''};
function choose(choice:string){setAnswers(v=>({...v,[q.id]:{choice,note:v[q.id]?.note||''}}));}
function next(){if(!a.choice){setError('اختر الصورة الأقرب أو «غير متأكد» أو «خيار آخر».');return;}act(async()=>{await request({action:'save',room,answers});setNotice('حُفظت الإجابات');setExample(false);if(step===questions.length-1)setMode('review');else setStep(step+1);});}
function copy(){const url=location.origin+'/?room='+room;navigator.clipboard?.writeText(url).then(()=>setNotice('نُسخ رابط الجلسة')).catch(()=>setNotice('انسخ الرابط من الحقل أدناه.'));}
function exportWorkbook(){const blob=surveyWorkbook(data?.report||[{name:data?.me?.name||'',answers}]);const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='manoly-survey.xlsx';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportData(){const blob=new Blob([JSON.stringify({title:'منولي — رؤية العائلة',questions,results:data?.report||[{name:data?.me?.name,answers}]},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='manoly-answers.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function reportCards(list:{name:string;answers:Answers}[]){return list.map((p,pi)=><section className="person-map" key={pi}><div className="map-heading"><span className="eyebrow">MANOLY / خريطة الرؤية</span><h2>{p.name}</h2><p>اختيارات شخصية • أساس للنقاش وتصميم الهوية</p></div>{chapters.map((ch,ci)=><div className={'map-chapter chapter-'+ci} key={ch}><h3>{ch}</h3><div className="map-nodes">{questions.filter(q=>q.chapter===ci).map(q=>{const a=p.answers[q.id];return <div className="map-node" key={q.id}><small>{q.title}</small><strong>{a?.choice||'لم يُجب'}</strong>{a?.note&&<p>{a.note}</p>}</div>})}</div></div>)}</section>);}
return <main><header className="topbar"><a className="wordmark" href="/" aria-label="بداية منولي">MANOLY<span>رؤية العائلة</span></a><a className="secondary no-print" href="/answers">عرض الإجابات</a><div className="top-note"><Users size={18}/><span>{data?`${data.count} مشارك`:'٨–٩ أفراد · رؤية واحدة'}</span></div></header>
{!ready?<div className="loading">جارٍ تحميل الجلسة…</div>:<>
{mode==='start'&&<section className="start-layout"><div className="start-copy"><span className="eyebrow">اكتشاف هوية العلامة</span><h1>صِف علامة <em>منولي</em><br/>كما تراها.</h1><p className="lead">اختر الصور والألوان الأقرب لرؤيتك.<br/>إجابات العائلة تكشف شخصية العلامة واتجاهها للسنوات الخمس القادمة.</p><form onSubmit={e=>{e.preventDefault();enter();}}><label htmlFor="name">بأي اسم نبدأ؟</label><input id="name" maxLength={60} required value={name} onChange={e=>setName(e.target.value)} placeholder="اسمك فقط" autoComplete="given-name"/><button className="primary" disabled={busy||!!data?.revealed}>{busy?'جارٍ الدخول…':room?'انضم إلى الاستبيان':'ابدأ اكتشاف العلامة'}<ArrowLeft size={20}/></button></form><p className="fine">دون كلمة مرور. الاسم للتعريف، وليس للتحقّق من الهوية.<br/>٢٤ سؤالًا مصوّرًا · لا إجابات صحيحة أو خاطئة</p>{room&&data?.revealed&&<p>هذه الجلسة انتهت. <a href="/">ابدأ جلسة جديدة</a></p>}</div><div className="start-art"><div className="art-title">اليوم <span>←</span> ٣ سنوات <span>←</span> ٥ سنوات</div><Picture o={{scene:4,label:'العائلة تبني رؤيتها'}}/><div className="color-ribbon"><span/><span/><span/><span/></div><div className="art-caption">كل اختيار يوضّح جزءًا من شخصية العلامة.</div></div></section>}
{mode==='play'&&<section className="play"><div className="game-meta"><span className="eyebrow">{chapters[q.chapter]}</span><span>{data?.me?.name} · {step+1} / ٢٤</span></div><Progress value={(step+1)/24*100} aria-label="تقدم الإجابة"/><div className="chapter-track">{chapters.map((c,j)=><span className={j===q.chapter?'active':''} key={c}>{String(j+1).padStart(2,'0')} {c}</span>)}</div><div className="question-title"><h1>{q.title}</h1><p>{q.hint}</p></div><RadioGroup className={'picture-grid '+(q.id==='palette'?'palette-grid':'')} value={a.choice} onValueChange={choose} aria-label={q.title} dir="rtl">{q.options.map((o,j)=><label className={'choice '+(a.choice===o.label?'selected':'')} key={o.label}><Picture o={o}/><div className="choice-caption"><RadioGroupItem value={o.label} id={'option-'+j}/><span><strong>{o.label}</strong>{o.description&&<small>{o.description}</small>}</span>{a.choice===o.label&&<Check size={18}/>}</div></label>)}</RadioGroup><div className="below-cards"><div className="extra-options">{EXTRA_OPTIONS.map(label=><button key={label} className={'unsure '+(a.choice===label?'chosen':'')} onClick={()=>choose(label)}>{label}</button>)}</div><button className="example-toggle" onClick={()=>setExample(!example)} aria-expanded={example}><Lightbulb size={19}/>وضّح لي بمثال</button></div>{example&&<div className="example"><div className="example-steps"><span>اختيار</span><ArrowLeft/><span>سبب</span><ArrowLeft/><span>أثر على العميل</span></div><p>{q.example}</p></div>}<label className="note-label" htmlFor="note">لماذا اخترت هذا؟ <span>اختياري — اذكر شرطك أو مثالًا</span></label><textarea id="note" maxLength={1200} value={a.note} placeholder="رأيك هو الجزء المهم من الصورة…" onChange={e=>setAnswers(v=>({...v,[q.id]:{choice:a.choice,note:e.target.value}}))}/><div className="game-actions"><button className="primary" disabled={busy} onClick={next}>{busy?'جارٍ الحفظ…':step===23?'راجع خريطة إجاباتك':'احفظ وتابع'}<ArrowLeft size={19}/></button><button className="secondary" disabled={busy||step===0} onClick={()=>{setStep(step-1);setExample(false);setError('');}}><ArrowRight size={18}/>السابق</button></div><p className="fine">تُحفظ إجاباتك عند المتابعة. عرض إجابات العائلة محمي بكلمة سر.</p></section>}
{mode==='review'&&<section className="review"><div className="section-title"><span className="eyebrow">اكتملت اختياراتك</span><h1>هذه رؤيتك. هل تعبّر عنك؟</h1><p>راجع الاختيارات قبل الإرسال النهائي. بعدها تُقفل الإجابات.</p></div><div className="review-grid">{questions.map((q,k)=><button className="review-item" key={q.id} onClick={()=>{setStep(k);setMode('play');}}><small>{k+1}. {q.title}</small><strong>{answers[q.id]?.choice||'لم يُجب'}</strong><span>تعديل</span></button>)}</div><button className="primary" disabled={busy} onClick={()=>act(async()=>{await request({action:'save',room,answers,done:true});await load(room);setMode('waiting');})}>{busy?'جارٍ الإرسال…':'اعتمد إجاباتي'}<Check/></button></section>}
{mode==='waiting'&&<section className="waiting"><div className="done-icon"><Flag size={36}/></div><span className="eyebrow">وصلت إلى نهاية الرحلة</span><h1>رؤيتك أصبحت جزءًا من الصورة.</h1><p>أنهى {data?.complete} من {data?.count} مشاركين إجاباتهم.</p><div className="participant-list">{data?.participants?.map((p,i)=><div key={i}><span>{p.name}</span><b>{p.done?'أكمل الإجابات':'يختار الآن'}</b></div>)}</div><div className="invite"><label htmlFor="invite">رابط بقية أفراد العائلة</label><div><input id="invite" readOnly value={typeof location!=='undefined'?location.origin+'/?room='+room:''}/><button className="secondary" onClick={copy}><Copy size={18}/>نسخ</button></div><p className="fine">الرابط يتيح الانضمام إلى الجلسة. أرسله لأفراد العائلة المقصودين فقط.</p></div>{data?.host&&<div className="host-box"><h3>أنت منظّم الجلسة</h3><a href="/answers" className="secondary">عرض الإجابات بكلمة السر</a><p>انتظر انضمام ٨–٩ أفراد. عرض النتائج يغلق الانضمام والتعديل.</p><button className="primary" disabled={busy||data.count<2||data.complete!==data.count} onClick={()=>act(async()=>{await request({action:'reveal',room});await load(room);})}>أنهوا جميعًا — أغلق الجلسة</button></div>}<div className="game-actions"><button className="secondary" onClick={()=>{load(room).catch(e=>setError(e.message));}}>تحديث الحالة</button><button className="secondary" onClick={()=>setMode('my-map')}>خريطتي الشخصية</button></div></section>}
{mode==='my-map'&&<><div className="toolbar"><button className="secondary" onClick={()=>setMode('waiting')}>العودة للجلسة</button><button className="primary" onClick={()=>window.print()}><Printer/>طباعة A4 / حفظ PDF</button><button className="secondary" onClick={exportData}><Download/>تنزيل الإجابات</button></div>{reportCards([{name:data?.me?.name||'',answers}])}</>}
{mode==='results'&&data?.report&&<section className="results"><div className="section-title no-print"><span className="eyebrow">الصورة المشتركة</span><h1>وجوه مختلفة. مستقبل نرسمه معًا.</h1><p>{data.report.length} إجابات فعلية. الاختلاف نقطة نقاش، وليس خطأ.</p></div><div className="toolbar"><button className="primary" onClick={()=>window.print()}><Printer/>خرائط A4 / حفظ PDF</button><button className="secondary" onClick={exportData}><Download/>تنزيل الإجابات JSON</button><button className="primary" onClick={exportWorkbook}><Download/>ملف Excel — الإجابات والنسب والرسوم</button></div><p className="method-note">النسبة = عدد اختيار الخيار ÷ عدد المجيبين عن السؤال. الإجابات الناقصة خارج المقام. «غير متأكد» خيار مستقل. الإجابات القديمة المدمجة تبقى كما وردت. هذه آراء العائلة، وليست دليلًا على رأي السوق.</p><section className="family-map"><span className="eyebrow">MANOLY / خريطة العائلة</span><h2>أين نلتقي؟ وأين نختلف؟</h2><div className="consensus-grid">{stats.map(q=><article key={q.id} className={'consensus chapter-'+q.chapter}><h3>{q.title}</h3>{q.options.map((o,j)=><div className="vote" key={o.label}><div><span>{o.label}</span><b>{o.count} · {percent(o.percentage)}</b></div><div className="vote-track"><span style={{width:(o.percentage||0)*100+'%',background:['#2547dd','#bd4169','#16826d','#b77313','#7256ba','#53617a','#2088a8'][j%7]}}/></div></div>)}<div className="missing-count">أجاب: {q.answered} / {q.total} · لم يُجب: {q.missing}</div><small>{q.answered===0?'لا إجابات بعد':q.options.filter(o=>o.count>0).length===1?'اتفاق في الاختيار — راجعوا الأسباب':'اختيارات مختلفة — ناقشوا الأسباب'}</small></article>)}</div></section><section className="brief"><h2>من الإجابات إلى موجز الشعار</h2><p>تُقرأ هذه الاتجاهات مع الأسباب الفردية؛ التصويت وحده لا يعتمد تصميمًا.</p>{['customer','strength','five','palette','style','preserve','redline'].map(id=>{const q=questions.find(x=>x.id===id)!;const opts=Array.from(new Set(data.report!.map(p=>p.answers[id]?.choice).filter(Boolean)));return <div key={id}><strong>{q.title}</strong><p>{opts.join(' / ')}</p></div>})}<p>الخطوة التالية في الجلسة: اختبروا وضوح الشعار وتميّزه وتطبيقه مع العملاء، ثم اتفقوا على اتجاه التصميم والميزانية والموعد.</p></section>{reportCards(data.report)}</section>}
</>}
{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="save-notice no-print" role="status">{notice}</div>}
{room&&mode==='play'&&data?.host&&<details className="invite-inline no-print"><summary>دعوة أفراد العائلة</summary><p>انسخ الرابط وأرسله لبقية المشاركين.</p><input readOnly aria-label="رابط دعوة العائلة" value={typeof location!=='undefined'?location.origin+'/?room='+room:''}/><button className="secondary" onClick={copy}><Copy size={18}/>نسخ الرابط</button></details>}
<footer className="no-print">منولي • اكتشاف الهوية والرؤية <span>الصور توضيحية، وليست صورًا فعلية للشركة.</span></footer></main>;
}
