import {database} from '@/db/raw';
import {questions} from '@/app/questions';
import {EXTRA_OPTIONS,LEGACY_OPTION,LEGACY_PALETTE_OPTIONS} from '@/app/survey-summary';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200,headers:Record<string,string>={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store',...headers}});
const cookie=(r:Request,key:string)=>r.headers.get('cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith(key+'='))?.slice(key.length+1)||'';
const valid=(s:unknown)=>typeof s==='string'&&/^[a-f0-9-]{36}$/.test(s);
const cookieHeader=(room:string,id:string)=>`manoly_${room}=${id}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`;
export async function GET(req:Request){try{const room=new URL(req.url).searchParams.get('room');if(!valid(room))return json({error:'رابط الجلسة غير صالح.'},400);const db=database();const r=await db.prepare('SELECT id,host,revealed FROM rooms WHERE id=?').bind(room).first<any>();if(!r)return json({error:'الجلسة غير موجودة.'},404);const id=cookie(req,'manoly_'+room);const me=await db.prepare('SELECT id,name,answers,done FROM members WHERE id=? AND room=?').bind(id,room).first<any>();const all=await db.prepare('SELECT id,name,done FROM members WHERE room=? ORDER BY created').bind(room).all<any>();const base={room,revealed:!!r.revealed,count:all.results.length,complete:all.results.filter((m:any)=>m.done).length};if(!me)return json({...base,me:null});const report=null;return json({...base,host:r.host===id,me:{name:me.name,answers:JSON.parse(me.answers),done:!!me.done},participants:all.results.map((m:any)=>({name:m.name,done:!!m.done})),report});}catch(e){console.error('game-load',e);return json({error:'تعذّر تحميل الجلسة. حاول مجددًا.'},503);}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return json({error:'طلب غير مسموح.'},403);const raw=await req.text();if(raw.length>60000)return json({error:'الإجابة طويلة جدًا.'},413);const p=JSON.parse(raw),db=database();if(p.action==='create'){const name=String(p.name||'').trim();if(!name||name.length>60)return json({error:'اكتب اسمًا من ١ إلى ٦٠ حرفًا.'},400);const room=crypto.randomUUID(),id=crypto.randomUUID(),now=new Date().toISOString();await db.batch([db.prepare('INSERT INTO rooms (id,host,created) VALUES (?,?,?)').bind(room,id,now),db.prepare('INSERT INTO members (id,room,name,created) VALUES (?,?,?,?)').bind(id,room,name,now)]);return json({room},201,{'Set-Cookie':cookieHeader(room,id)});}
if(!valid(p.room))return json({error:'جلسة غير صالحة.'},400);const r=await db.prepare('SELECT * FROM rooms WHERE id=?').bind(p.room).first<any>();if(!r)return json({error:'الجلسة غير موجودة.'},404);const id=cookie(req,'manoly_'+p.room);let me=await db.prepare('SELECT * FROM members WHERE id=? AND room=?').bind(id,p.room).first<any>();if(p.action==='join'){if(me)return json({room:p.room});if(r.revealed)return json({error:'انتهت الجلسة؛ لا يمكن إضافة مشاركين.'},409);const name=String(p.name||'').trim();if(!name||name.length>60)return json({error:'اكتب اسمًا من ١ إلى ٦٠ حرفًا.'},400);const mid=crypto.randomUUID();const result=await db.prepare('INSERT INTO members (id,room,name,created) SELECT ?,?,?,? WHERE (SELECT revealed FROM rooms WHERE id=?)=0 AND (SELECT COUNT(*) FROM members WHERE room=?) < 9 AND NOT EXISTS (SELECT 1 FROM members WHERE room=? AND name=?)').bind(mid,p.room,name,new Date().toISOString(),p.room,p.room,p.room,name).run();if(!result.meta.changes)return json({error:'الاسم مستخدم أو اكتمل العدد (٩). استخدم اسمًا مميزًا إذا لزم.'},409);return json({room:p.room},201,{'Set-Cookie':cookieHeader(p.room,mid)});}
if(!me)return json({error:'ادخل باسمك أولًا.'},401);if(p.action==='reveal'){if(r.host!==id)return json({error:'منظّم الجلسة وحده يعرض النتائج.'},403);const counts=await db.prepare('SELECT COUNT(*) AS total,SUM(done) AS done FROM members WHERE room=?').bind(p.room).first<any>();if(counts.total<2||counts.total!==counts.done)return json({error:'يلزم مشاركان على الأقل، وأن يُنهي جميع المنضمين إجاباتهم.'},409);const updated=await db.prepare('UPDATE rooms SET revealed=1 WHERE id=? AND NOT EXISTS (SELECT 1 FROM members WHERE room=? AND done=0)').bind(p.room,p.room).run();if(!updated.meta.changes)return json({error:'انضم مشارك جديد. انتظر انتهاء إجاباته.'},409);return json({ok:true});}
if(p.action==='save'){if(r.revealed||me.done)return json({error:'الإجابات النهائية مقفلة.'},409);const a=p.answers;if(!a||typeof a!=='object'||Array.isArray(a))return json({error:'إجابات غير صالحة.'},400);const clean:Record<string,any>={};for(const [k,v] of Object.entries(a)){const q=questions.find(x=>x.id===k);const x=v as any;const allowed=q?[...q.options.map(o=>o.label),...EXTRA_OPTIONS,LEGACY_OPTION,...(q.id==='palette'?LEGACY_PALETTE_OPTIONS:[])]:[];if(!q||!x||typeof x.choice!=='string'||!allowed.includes(x.choice)||typeof x.note!=='string'||x.note.length>1200)return json({error:'تحقّق من خياراتك وطول التفسير.'},400);clean[k]={choice:x.choice,note:x.note};}if(p.done&&questions.some(q=>!clean[q.id]?.choice))return json({error:'أكمل اختيارات الأسئلة أولًا.'},400);await db.prepare('UPDATE members SET answers=?,done=? WHERE id=? AND room=?').bind(JSON.stringify(clean),p.done?1:0,id,p.room).run();return json({ok:true});}return json({error:'طلب غير معروف.'},400);}catch(e){console.error('game-save',e);return json({error:'تعذّر الحفظ. إجابتك باقية على الشاشة؛ حاول مجددًا.'},503);}}
