'use client';
import {useEffect,useState} from 'react';
import {questions} from '../questions';
import {summarize,percent,type SurveyRecord} from '../survey-summary';
import {surveyWorkbook} from '../xlsx-export';
type Entry=SurveyRecord&{done:boolean};
export default function AnswersPage(){const [logged,setLogged]=useState(false),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[sessions,setSessions]=useState<any[]>([]),[selected,setSelected]=useState(''),[records,setRecords]=useState<Entry[]>([]);
async function fetchJson(url:string,options?:RequestInit){const r=await fetch(url,options);const d=await r.json();if(r.status===401){setLogged(false);setRecords([]);setSessions([]);}if(!r.ok)throw new Error(d.error);return d;}
async function reload(){const d=await fetchJson('/api/results');setSessions(d.sessions);setLogged(true);}
useEffect(()=>{reload().catch(()=>{});},[]);
async function choose(id:string){setSelected(id);setRecords([]);setError('');setBusy(true);try{const d=await fetchJson('/api/results?room='+encodeURIComponent(id));setRecords(d.report);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await fetchJson('/api/results',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});setPassword('');await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
async function logout(){try{await fetchJson('/api/results',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});setLogged(false);setRecords([]);setSessions([]);setSelected('');}catch(e){setError((e as Error).message);}}
function download(){const url=URL.createObjectURL(surveyWorkbook(records)),a=document.createElement('a');a.href=url;a.download='manoly-answers.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
return <main><header className="topbar no-print"><a className="wordmark" href="/">MANOLY<span>رؤية العائلة</span></a><a className="secondary" href="/">الاستبيان</a>{logged&&<button className="secondary" onClick={logout}>قفل الإجابات</button>}</header><div className="section-title"><h1>إجابات العائلة</h1><p>{logged?'اختر الجلسة لعرض الأسماء والإجابات والنسب.':'أدخل كلمة السر للوصول إلى نتائج الاستبيان.'}</p></div>{!logged?<form onSubmit={login} className="answers-login"><label htmlFor="results-password">كلمة السر</label><input id="results-password" type="password" autoComplete="current-password" inputMode="numeric" value={password} onChange={e=>setPassword(e.target.value)} required maxLength={100}/><button className="primary" disabled={busy}>{busy?'جارٍ التحقّق…':'عرض الإجابات'}</button></form>:<><div className="no-print"><button className="secondary" disabled={busy} onClick={()=>reload().catch(e=>setError(e.message))}>تحديث الجلسات</button><div className="review-grid">{sessions.map(s=><button className="review-item" key={s.id} onClick={()=>choose(s.id)} aria-pressed={selected===s.id}><strong>جلسة {s.hostName||'العائلة'}</strong><small>{new Date(s.created).toLocaleString('ar')} · {s.count} مشارك · {s.complete} أكملوا</small><span>{selected===s.id?'الجلسة المحددة':'عرض الإجابات'}</span></button>)}</div>{sessions.length===0&&<p>لا توجد جلسات محفوظة حتى الآن.</p>}</div>{busy&&<p role="status">جارٍ التحميل…</p>}{selected&&!busy&&<><div className="toolbar"><button className="primary" onClick={download}>تنزيل Excel — الأسماء والنسب والرسوم</button><button className="secondary" onClick={()=>window.print()}>طباعة A4 / حفظ PDF</button><button className="secondary" onClick={()=>choose(selected)}>تحديث الإجابات</button></div><p className="method-note">تظهر الإجابات المحفوظة، بما فيها الاستبيانات غير المكتملة. النسبة من المجيبين عن كل سؤال؛ الناقص منفصل. هذه آراء العائلة، وليست قياسًا لرأي السوق.</p><div className="consensus-grid">{summarize(records).map(q=><article className={'consensus chapter-'+q.chapter} key={q.id}><h3>{q.title}</h3>{q.options.map((o,i)=><div className="vote" key={o.label}><div><span>{o.label}</span><b>{o.count} · {percent(o.percentage)}</b></div><div className="vote-track"><span style={{width:(o.percentage||0)*100+'%',background:['#2547dd','#bd4169','#16826d','#b77313'][i%4]}}/></div></div>)}<p className="missing-count">أجاب: {q.answered} / {q.total} · لم يُجب: {q.missing}</p></article>)}</div>{records.map((p,i)=><section className="person-map" key={i}><h2>{p.name}</h2><p>{p.done?'إجابات نهائية':'لم يُكمل الاستبيان بعد'}</p><div className="map-nodes">{questions.map(q=><div className="map-node" key={q.id}><small>{q.title}</small><strong>{p.answers[q.id]?.choice||'لم يُجب'}</strong><p>{p.answers[q.id]?.note||'دون تفسير إضافي'}</p></div>)}</div></section>)}</>}</>}{error&&<p className="error" role="alert">{error}</p>}</main>;
}
